"""
Evaluate Performance Script
This script checks the 'redaction_log.json' generated by redactor.py against
a hardcoded list of known PII (Ground Truth) to calculate Precision and Recall.
"""

import json

# This is the "Ground Truth" - the actual PII we know is in the document.
# We embed it here so it's easy to read and explain in an interview.
GROUND_TRUTH = {
    "PERSON": [
        "Kushal Subbayya Hegde", "Pushpa Kushal Hegde", "Rajesh Kushal Hegde", 
        "Rohit Kushal Hegde", "Rakhi Girija Shetty", "Dinesh Hirachand Munot", 
        "Ajay Shriram Patil", "Ram Kumar Tiwari", "Indu Jacob", "Sandesh Bhagwat", 
        "Amod Joshi", "Sarthak Malvadkar", "Rupal K. Sancheti", "Salil Ajay Bhargava", 
        "Jabeen Ajay Menon", "Ajay Menon", "Sunil Nagayya Shetty", "Sangeeta Ramprasad Rai", 
        "Amanda Whitfield", "Rajiv Menon"
    ],
    "EMAIL_ADDRESS": [
        "amanda.whitfield84@sample-mail.com", "rajiv.menon77@sample-mail.in"
    ],
    "PHONE_NUMBER": [
        "+1 (415) 555-0198", "+91 98765 43210"
    ],
    "ADDRESS": [
        "11/3, 11/4 and 11/5, Village Birdewadi, Chakan Taluka - Khed, Pune - 410 501, Maharashtra, India",
        "201, Tower-2, Montreal Business Centre, Off Pallod Farms, Baner, Pune - 411 045, Maharashtra, India",
        "PCNTDA Green Building, Block A, 1st & 2nd Floor, Near Akurdi Railway Station, Akurdi, Pune - 411 044, Maharashtra",
        "742 Evergreen Terrace, Apt 4B, Springfield, IL 62704, USA",
        "Flat 302, Sunrise Apartments, MG Road, Bengaluru - 560001, Karnataka, India"
    ],
    "DATE_TIME": [
        "14-March-1988", "02/11/1990"
    ],
    "US_SSN": [
        "923-45-6781"
    ],
    "CREDIT_CARD": [
        "4111 1111 1111 1234", "5500 0000 0000 0004"
    ],
    "IP_ADDRESS": [
        "192.168.117.42", "10.0.212.55"
    ],
    "COMPANY_NAME": [
        "Northbridge Analytics Pvt. Ltd.", "Meridian Cable & Wire Traders LLP"
    ]
}

def evaluate(log_file):
    print("Loading redaction logs...")
    try:
        with open(log_file, "r") as f:
            logs = json.load(f)
    except FileNotFoundError:
        print(f"Error: {log_file} not found. Please run redactor.py first.")
        return

    # Extract all the unique strings that our tool flagged as PII
    detected_strings = set([log["original"].strip() for log in logs])
    
    # Flatten our ground truth dictionary into a single list of actual PII strings
    actual_pii = []
    for category, items in GROUND_TRUTH.items():
        actual_pii.extend(items)
        
    actual_pii_set = set(actual_pii)
    
    # Calculate True Positives (things we correctly caught)
    # We use a loose match to give credit if Presidio caught part of a long address
    true_positives = set()
    for detected in detected_strings:
        for actual in actual_pii_set:
            if detected in actual or actual in detected:
                true_positives.add(actual)
                
    # Calculate False Negatives (things we missed completely)
    false_negatives = actual_pii_set - true_positives
    
    # Calculate False Positives (things we caught that weren't in the ground truth at all)
    # E.g. catching "52.5%" or a random transaction ID
    false_positives = set()
    for detected in detected_strings:
        is_tp = False
        for actual in actual_pii_set:
            if detected in actual or actual in detected:
                is_tp = True
                break
        if not is_tp:
            false_positives.add(detected)

    print("\n" + "="*50)
    print(" EVALUATION REPORT")
    print("="*50)
    
    print(f"Total True Positives (Correctly Detected): {len(true_positives)}")
    print(f"Total False Positives (Accidentally Detected): {len(false_positives)}")
    print(f"Total False Negatives (Missed): {len(false_negatives)}")
    
    print("\n--- Missed PII (False Negatives) ---")
    if false_negatives:
        for fn in false_negatives:
            print(f" - {fn}")
    else:
        print(" (None! Perfect Recall!)")
        
    print("\n--- Over-redacted PII (False Positives Sample) ---")
    if false_positives:
        for i, fp in enumerate(list(false_positives)[:5]):
            print(f" - {fp}")
        if len(false_positives) > 5:
            print(f"   ... and {len(false_positives) - 5} more.")
    else:
        print(" (None! Perfect Precision!)")
        
    # Metrics
    tp = len(true_positives)
    fp = len(false_positives)
    fn = len(false_negatives)
    
    # Precision: Out of all the things we flagged, how many were actually PII?
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    
    # Recall: Out of all the actual PII in the document, how many did we catch?
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    
    print("\n" + "="*50)
    print(f" PRECISION: {precision:.2%} (Did we avoid redacting non-PII?)")
    print(f" RECALL:    {recall:.2%} (Did we catch everything we were supposed to?)")
    print("="*50)

if __name__ == "__main__":
    evaluate("redaction_log.json")
